### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by carstingaxion** [figuren-theater/ft-seo#9]
```[tasklist]
### Stories
- [ ] https://github.com/figuren-theater/ft-seo/issues/11
- [ ] https://github.com/figuren-theater/ft-seo/issues/15
```

```[tasklist]
### Plugins
- [ ] https://github.com/figuren-theater/ft-seo/issues/16
- [ ] https://github.com/figuren-theater/ft-seo/issues/10
```

```[tasklist]
### misc. ToDos
- [ ] ...
```
